### ISSUE TITLE
Deprecated git.class

### ISSUE THREAD

**Issue by latot** [v-fox/gentoo_overlay#10]
Hi, this package is using that feature.

 * ERROR: games-emulation/dolphin-emu-3.0::v-fox failed (depend phase):
 *   git.eclass could not be found by inherit()
 * 
 * Call stack:
 *                ebuild.sh, line 584:  Called source '/var/lib/layman/v-fox/games-emulation/dolphin-emu/dolphin-emu-3.0.ebuild'
 *   dolphin-emu-3.0.ebuild, line   8:  Called inherit 'cmake-utils' 'eutils' 'flag-o-matic' 'games' 'git' 'pax-utils' 'wxwidgets'
 *                ebuild.sh, line 257:  Called die
 * The specific snippet of code:
 *   		[[ -z ${location} ]] && die "${1}.eclass could not be found by inherit()"
 * 
 * If you need support, post the output of `emerge --info '=games-emulation/dolphin-emu-3.0::v-fox'`,
 * the complete build log and the output of `emerge -pqv '=games-emulation/dolphin-emu-3.0::v-fox'`.
 * Working directory: '/usr/lib64/python3.3/site-packages'
 * S: '/var/tmp/portage/games-emulation/dolphin-emu-3.0/work/dolphin-emu-3.0'

Thx.

**Comment by Vality** [comment]
Solved this by removing the dolphin-enu-3.0 ebuild from the repo, this version is now extremely old and has been deleted from the main portage tree too.
