### ISSUE TITLE
ppsspp-9999-r4.ebuild

### ISSUE THREAD

**Issue by latot** [v-fox/gentoo_overlay#11]
Hi, the function "cmake-utils_src_unpack" in the ebuild don't exist, and don't is necessary.

Thx.

**Comment by Vality** [comment]
Sorry, I dont understand what you mean. Could you please rephrase your issue?

**Comment by latot** [comment]
from ebuild
```
		qt4-r2_src_unpack
	else
		cmake-utils_src_unpack
	fi
}

src_prepare() {
```

function cmake-utils_src_unpack don't exist.
https://devmanual.gentoo.org/eclass-reference/cmake-utils.eclass/

**Comment by Vality** [comment]
Are you suggesting we just remove the call to it, or is there something else we need to replace it with? If you like and the change is complex you could send a pull request?

**Comment by latot** [comment]
https://github.com/v-fox/gentoo_overlay/pull/21

**Comment by Vality** [comment]
Request merged, thankyou
