### ISSUE TITLE
PPSSPP Recomendation obuild

### ISSUE THREAD

**Issue by latot** [v-fox/gentoo_overlay#6]
Hi, you are using git submodule update --init to get the submodules of the repository, the problem is when you try emerge the package the system will download all the files of submodules without save, if i emerge again the system will download all again u.u well in the ebuild you can remove the line 

 git submodule update --init

and add

EGIT_HAS_SUBMODULES=1
EGIT_REPO_URI="git://github.com/hrydgard/ppsspp.git"

the EGIT_HAS_SUBMODULES will fetch the submodules but will save the files in the pc and the system don't will download all again, thx.

**Comment by Vality** [comment]
Implemented the suggestion, thanks.
