### ISSUE TITLE
PPSSPP setup failed

### ISSUE THREAD

**Issue by latot** [v-fox/gentoo_overlay#7]
Hi, here are a problem in the installation:

Source compiled.
Test phase [not enabled]: games-emulation/ppsspp-9999-r3

Install ppsspp-9999-r3 into /var/tmp/portage/games-emulation/ppsspp-9999-r3/image/ category games-emulation
!!! doexe: /var/tmp/portage/games-emulation/ppsspp-9999-r3/work/ppsspp-9999/Qt/PPSSPPQt does not exist

ERROR: games-emulation/ppsspp-9999-r3::v-fox failed (install phase):
doexe failed

**Comment by Vality** [comment]
Please try resyncing the overlay, it is definitely fixed now. It looks like you have an outdated ebuild. They renamed the binary from PPSSPPQt to ppsspp so I am now running "newexe "${WORKDIR}"/"${P}"/Qt/ppsspp PPSSPPQt"

**Comment by latot** [comment]
Hi, the installation fails again u.u

log:

>>> Source compiled.
>>> Test phase [not enabled]: games-emulation/ppsspp-9999-r3

>>> Install ppsspp-9999-r3 into /var/tmp/portage/games-emulation/ppsspp-9999-r3/image/ category games-emulation
>>> Completed installing ppsspp-9999-r3 into /var/tmp/portage/games-emulation/ppsspp-9999-r3/image/

 * QA Notice: / installed in ${D}/${D}
 * QA Notice: /usr installed in ${D}/${D}
 * QA Notice: /usr/games installed in ${D}/${D}
 * QA Notice: /usr/games/bin installed in ${D}/${D}
 * QA Notice: /usr/games/bin/ppssppqt installed in ${D}/${D}
 * QA Notice: /usr/share installed in ${D}/${D}
 * QA Notice: /usr/share/games installed in ${D}/${D}
 * QA Notice: /usr/share/games/ppsspp installed in ${D}/${D}
 * QA Notice: /usr/share/games/ppsspp/PPSSPPQt installed in ${D}/${D}
 * ERROR: games-emulation/ppsspp-9999-r3::v-fox failed:
 *   Aborting due to QA concerns: 9 files installed in /var/tmp/portage/games-emulation/ppsspp-9999-r3/image/var/tmp/portage/games-emulation/ppsspp-9999-r3/image/
 * 
 * Call stack:
 *   misc-functions.sh, line 558:  Called install_qa_check
 *   misc-functions.sh, line 181:  Called source 'install_symlink_html_docs'
 *          05double-D, line  14:  Called DD_check
 *          05double-D, line  10:  Called die
 * The specific snippet of code:
 *   		die "Aborting due to QA concerns: ${INSTALLTOD} files installed in ${D%/}${D}"
 * 
 * If you need support, post the output of `emerge --info '=games-emulation/ppsspp-9999-r3::v-fox'`,
 * the complete build log and the output of `emerge -pqv '=games-emulation/ppsspp-9999-r3::v-fox'`.
 * The complete build log is located at '/var/tmp/portage/games-emulation/ppsspp-9999-r3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-emulation/ppsspp-9999-r3/temp/environment'.
 * Working directory: '/var/tmp/portage/games-emulation/ppsspp-9999-r3/image'
 * S: '/var/tmp/portage/games-emulation/ppsspp-9999-r3/work/ppsspp-9999'
!!! post install failed; exiting.

**Comment by Vality** [comment]
I think I have sussed the issue. It does not like us explicitly using the ${D} variable any more. I think I have fixed it now, could you try again?

**Comment by latot** [comment]
now pass the install phase but the app is installed on /usr/share/games/ppsspp/PPSSPPQt

**Comment by Vality** [comment]
That is correct, due to limitations of ppsspp the binary gets placed there, however you run the script in /usr/games/bin to launch it.
