### ISSUE TITLE
Digest verification failed

### ISSUE THREAD

**Issue by latot** [v-fox/gentoo_overlay#9]
Hi again, log:

 * Digest verification failed:
 * /var/lib/layman/v-fox/games-rpg/soulfu/soulfu-1.5.2.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 933
 * Expected: 936

 * Digest verification failed:
 * /var/lib/layman/v-fox/media-libs/libsdl/libsdl-1.2.15-r5.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 4708
 * Expected: 4702

Thx

**Comment by Vality** [comment]
Hey, could you check if this is fixed now, I just pushed out a patch?

**Comment by latot** [comment]
Hi, thx is fixed :D

**Comment by Vality** [comment]
Wonderful, thanks for the warning.
